from odoo import models, fields

class FlownTicket(models.Model):
    _name = 'flown.ticket'
    _description = 'Flown Ticket'

    date = fields.Date(string='Date', required=True)
    coupon_issued_created = fields.Datetime(string='CouponIssuedCreated')
    coupon_issued_modified = fields.Datetime(string='CouponIssuedModified' )

    pnr_alphanumeric = fields.Char(string='PNR alphanumeric')
    iata_ticket_number = fields.Char(string='IATA ticket number')
    iata_ticket_check_digit = fields.Char(string='IATA ticket check digit')
    coupon_order_on_ticket = fields.Char(string='Coupon order on ticket')
    coupon_order_on_segment = fields.Char(string='Coupon order on segment')
    Original_iata_ticket_number = fields.Char(string='Original IATA ticket number')
    Original_iata_ticket_check_digit = fields.Char(string='Original IATA ticket check digit')
    exchanged_iata_ticket_number = fields.Char(string='Exchanged IATA ticket number')
    exchanged_iata_ticket_check_digit = fields.Char(string='Exchanged IATA ticket check digit')
    zenith_coupon_status = fields.Char(string='Zenith coupon status')
    aircraft_type = fields.Char(string='Aircraft type')
    arrival_element = fields.Char(string='Arrival element')
    continuation_element = fields.Char(string='Continuation element')
    class_of_service = fields.Char(string='Class of service')
    airline_designator = fields.Char(string='Airline designator')
    Flight_number = fields.Char(string='Flight number')
    local_dep_datetime = fields.Datetime(string='Local departure date-time')
    local_arr_datetime = fields.Datetime(string='Local arrival date-time')
    departure_airport = fields.Char(string='Departure airport')
    arrival_airport = fields.Char(string='Arrival airport')
    booking_class = fields.Char(string='Booking class')
    coupon_service = fields.Char(string='Coupon service')
    fare_basis_class = fields.Char(string='Fare basis class')
    point_of_sale = fields.Char(string='Point Of sale')
    point_of_sale_code = fields.Char(string='Point Of sale Code')
    payment_type_identifier = fields.Char(string='Payment type identifier')
    customer_name = fields.Char(string='Customer name')
    coupon_price_taxes_commission = fields.Char(string='Coupon price excl. taxes commission (sales currency)')
    coupon_price_taxes = fields.Char(string='Coupon price excl. taxes (sales currency)')
    total_turnover_amount = fields.Char(string='Total turnover amount (sales currency)')
    coupon_commission_amount = fields.Char(string='Coupon commission amount (sales currency)')
    total_taxes_already = fields.Char(string='TotalTaxesAlreadyIncludedinCPNEEquivalentFareWithoutTaxSaleCurrency')
    coupon_taxes_amount = fields.Char(string='Coupon taxes amount (sales currency)')
    iata_taxes_amount = fields.Char(string='IATA taxes amount (sales currency)')
    airline_taxes_amount = fields.Char(string='Airline taxes amount (sales currency)')
    yq_tax_amount = fields.Char(string='YQ tax amount (sales currency)')
    yr_tax_amount = fields.Char(string='YR tax amount (sales currency)')
    service_fee_taxes_amount = fields.Char(string='Service fee taxes amount (Sale currency)')
    issuance_tax_amount = fields.Char(string='Issuance tax amount (Sale currency)')
    total_amount = fields.Char(string='Total amount (sales currency)')
    total_amount_excl = fields.Char(string='Total amount excl. commission (sales currency)')
    coupon_penalty_amount = fields.Char(string='Coupon penalty amount (sales currency)')
    excess_baggage_weight = fields.Char(string='Excess baggage weight')
    excess_baggage_fee_collected = fields.Char(string='Excess baggage fee collected through Zenith (sales currency)')
    acm = fields.Char(string='ACM (sales currency)')
    adm = fields.Char(string='ADM (sales currency)')
    coupon_mileage = fields.Char(string='Coupon mileage')
    ticket_mileage = fields.Char(string='Ticket mileage')
    pnr_of_operating_airline = fields.Char(string='PNR of operating airline')
    designator_of_operating_airline = fields.Char(string='Designator of operating airline')
    flight_number_on_operating_airline = fields.Char(string='Flight number on operating airline')
    booking_class_on_operating_airline = fields.Char(string='Booking class on operating airline')
    pnr_of_marketing_airline = fields.Char(string='PNR of marketing airline')
    designator_of_marketing_airline = fields.Char(string='Designator of marketing airline')
    flight_number_of_marketing_airline = fields.Char(string='Flight number of marketing airline')
    sales_currency = fields.Char(string='Sales currency')
    iata_passenger_type = fields.Char(string='IATA passenger type')
    passenger_civility = fields.Char(string='Passenger civility')
    passenger_surname = fields.Char(string='Passenger surname')
    passenger_first_name = fields.Char(string='Passenger first name')
    datetime_lt_of_issuance = fields.Datetime(string='Date-time (LT) of issuance')

    customer_id = fields.Many2one('res.partner', string='Customer ID')
    customer_ref = fields.Char(string='Customer Reference')
    export_id = fields.Integer(string='Coupon Accounting Export')
    # ID_PNR = fields.Integer(string='PNR')
    # ID_Company = fields.Integer(string='Company')
    # RCIRLoc = fields.Char(string='RCIRLoc')
    # GDSCRSPartnerRCIRLoc = fields.Integer(string='GDSCRSPartnerRCIRLoc')
    # ID_Customer = fields.Integer(string='Customer')
    # ID_CustomerType = fields.Integer(string='Customer Type')
    # ID_CouponIssued = fields.Integer(string='Coupon Issued')
    # ID_CouponExchange = fields.Integer(string='Coupon Exchange')
    # ID_CPNAeropackStatus = fields.Integer(string='CPNAeropack Status')
    # ID_TravelCheck1 = fields.Integer(string='Travel Check 1')
    # ID_TravelCheck2 = fields.Integer(string='Travel Check 2')
    # CouponIssuedCreator = fields.Integer(string='Coupon Issued Creator')
    # CouponIssuedCreated = fields.Datetime(string='Coupon Issued Created')
    # CouponIssuedModifier = fields.Integer(string='Coupon Issued Modifier')
    # CouponIssuedModified = fields.Datetime(string='Coupon Issued Modified')
    # ID_RefundType = fields.Integer(string='Refund Type')
    # ID_ModifiableType = fields.Integer(string='Modifiable Type')
    # CPNBoolIsServiceCoupon = fields.Boolean(string='Is Service Coupon')
    # ID_AeropackFareBasisClass = fields.Integer(string='Aeropack Fare Basis Class')
    # PTSFareBasisClass = fields.Char(string='PTSFare Basis Class')
    # PTSFareBasisClassLevel = fields.Float(string='PTSFare Basis Class Level')
    # CPNOrderOnTicket = fields.Integer(string='Order On Ticket')
    # CPNSegmentOrder = fields.Integer(string='Segment Order')
    # CPNEEquivalentFareWithoutTaxSaleCurrency = fields.Float(string='Equivalent Fare Without Tax (Sale Currency)')
    # CPNEEquivalentFareWithoutTaxBaseCurrency = fields.Float(string='Equivalent Fare Without Tax (Base Currency)')
    # CPNFCommissionAmountSaleCurrency = fields.Float(string='Fare Commission Amount (Sale Currency)')
    # CPNFCommissionAmountBaseCurrency = fields.Float(string='Fare Commission Amount (Base Currency)')
    # CPNHNetFareWithoutTaxSaleCurrency = fields.Float(string='Net Fare Without Tax (Sale Currency)')
    # CPNHNetFareWithoutTaxBaseCurrency = fields.Float(string='Net Fare Without Tax (Base Currency)')
    # CPNTaxAmountSaleCurrency = fields.Float(string='Tax Amount (Sale Currency)')
    # CPNTaxAmountBaseCurrency = fields.Float(string='Tax Amount (Base Currency)')
    # CPNTNetFareToPaySaleCurrency = fields.Float(string='Net Fare To Pay (Sale Currency)')
    # CPNTNetFareToPayBaseCurrency = fields.Float(string='Net Fare To Pay (Base Currency)')
    # CPNPenaltyAmountSaleCurrency = fields.Float(string='Penalty Amount (Sale Currency)')
    # CPNPenaltyAmountBaseCurrency = fields.Float(string='Penalty Amount (Base Currency)')
    # CPNNetFareToPayPlusPenaltyAmountSaleCurrency = fields.Float(string='Net Fare To Pay Plus Penalty Amount (Sale Currency)')
    # CPNNetFareToPayPlusPenaltyAmountBaseCurrency = fields.Float(string='Net Fare To Pay Plus Penalty Amount (Base Currency)')
    # ACMAmountInBaseCurrency = fields.Float(string='ACM Amount (Base Currency)')
    # ACMAmountInSaleCurrency = fields.Float(string='ACM Amount (Sale Currency)')
    # ADMAmountInBaseCurrency = fields.Float(string='ADM Amount (Base Currency)')
    # ADMAmountInSaleCurrency = fields.Float(string='ADM Amount (Sale Currency)')
    # OtherIncomesAmountInBaseCurrency = fields.Float(string='Other Incomes Amount (Base Currency)')
    # OtherIncomesAmountInSaleCurrency = fields.Float(string='Other Incomes Amount (Sale Currency)')
    # AirlineTaxesAmountInSaleCurrency = fields.Float(string='Airline Taxes Amount (Sale Currency)')
    # AirlineTaxesAmountInBaseCurrency = fields.Float(string='Airline Taxes Amount (Base Currency)')
    # EBDExcedentComment = fields.Char(string='EBD Excedent Comment')
    # EBDAmountExcessBagPayedSaleCurrency = fields.Float(string='EBD Amount Excess Bag Payed (Sale Currency)')
    # EBDAmountExcessBagPayedBaseCurrency = fields.Float(string='EBD Amount Excess Bag Payed (Base Currency)')
    # EBDExcedentBagWeight = fields.Float(string='EBD Excedent Bag Weight')
    # EBDMeasureQualifier = fields.Char(string='EBD Measure Qualifier')
    # CPNSACNumber = fields.Char(string='CPN SAC Number')
    # CPNVAD = fields.Char(string='CPN VAD')
    # FormOfPayment = fields.Char(string='Form Of Payment')
    # ID_PaymentMode = fields.Float(string='Payment Mode')
    # ID_FormOfPayment = fields.Float(string='Form Of Payment')
    # ID_Flight = fields.Integer(string='Flight')
    # ID_CityPair = fields.Integer(string='City Pair')
    # ID_AircraftType = fields.Integer(string='Aircraft Type')
    # TVLAircraftType = fields.Char(string='TVL Aircraft Type')
    # ID_CabinClassOfService = fields.Integer(string='Cabin Class Of Service')
    # TVLCabinClassOfServiceCode = fields.Char(string='TVL Cabin Class Of Service Code')
    # TVLAirlineDesignator = fields.Char(string='TVL Airline Designator')
    # TVLFlightNumber = fields.Char(string='TVL Flight Number')
    # ID_ClassCodePRBD = fields.Integer(string='Class Code PRBD')
    # TVLClassCodePRBD = fields.Char(string='TVL Class Code PRBD')
    # TVLIATADepartureAirport = fields.Char(string='TVL IATA Departure Airport')
    # TVLIATAArrivalAirport = fields.Char(string='TVL IATA Arrival Airport')
    # TVLDepartureDateAndHourLT = fields.Datetime(string='TVL Departure Date And Hour LT')
    # TVLArrivalDateAndHourLT = fields.Datetime(string='TVL Arrival Date And Hour LT')
    # TVLOperationRLOC = fields.Char(string='TVL Operation RLOC')
    # TVLOperationAirlineDesignator = fields.Char(string='TVL Operation Airline Designator')
    # TVLOperationFlightNumber = fields.Char(string='TVL Operation Flight Number')
    # TVLOperationClassCodePRBD = fields.Char(string='TVL Operation Class Code PRBD')
    # TVLMarketingRLOC = fields.Char(string='TVL Marketing RLOC')
    # TVLMarketingAirlineDesignator = fields.Char(string='TVL Marketing Airline Designator')
    # TVLMarketingFlightNumber = fields.Char(string='TVL Marketing Flight Number')
    # TVLMarketingClassCodePRBD = fields.Char(string='TVL Marketing Class Code PRBD')
    # CodeFlightType = fields.Char(string='Code Flight Type')
    # MONSaleCurrency = fields.Char(string='MON Sale Currency')
    # IFTFareCalculation = fields.Char(string='IFT Fare Calculation')